### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by hana-0612** [hana-0612/furima-36029#11]
ご確認よろしくお願いいたします。

#URL ：
　https://furima-36029.herokuapp.com/
#Basic認証のIDとパスワード ：
　ID: 　admin　、　PW:　2222  
#出品者用のメールアドレスとパスワード 
　メール：　aa@gmail.com　、　PW：　000000p
#購入者用のメールアドレスとパスワード
　メール：　b@gmail.com　、　PW：　000000p

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **入力された価格によって、販売手数料や販売利益の表示が変わるようにしましょう**
販売手数料、販売利益が表示されません。

- [x] **配送料の負担は、「---、着払い(購入者負担)、送料込み(出品者負担)」の3項目が表示されるようにしましょう（--- は初期値として設定すること）**
「発送元の地域」が設定されています。
<img width="930" alt="スクリーンショット 2021-09-27 10 39 41" src="https://user-images.githubusercontent.com/62644781/134833400-65686924-8cce-4f11-9f11-4525aa5b024d.png">


- [x] **発送元の地域は、「---」と47都道府県の合計48項目が表示されるようにしましょう（--- は初期値として設定すること）**
「配送料の負担」が設定されています。
<img width="930" alt="スクリーンショット 2021-09-27 10 39 48" src="https://user-images.githubusercontent.com/62644781/134833439-287ad31f-deed-4c16-ba87-11d2d6d69533.png">


- [x] **商品詳細ページに、商品出品時に登録した情報（商品名・商品画像・価格・配送料の負担・商品の説明・出品者名・カテゴリー・商品の状態・発送元の地域・発送日の目安）が、見本アプリと同様の形で表示されるようにしましょう**
価格が表示されていません。



修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by hana-0612** [comment]
ご確認いただきありがとうございます。
設定不備大変失礼いたしました。お手数ですが、再度ご確認お願いいたします。

#URL ：https://furima-36029.herokuapp.com/
#Basic認証のIDとパスワード ：
　ID: 　admin　、　PW:　2222  
#出品者用のメールアドレスとパスワード
　メール：　aa@gmail.com　、　PW：　000000p
#購入者用のメールアドレスとパスワード
　メール：　b@gmail.com　、　PW：　000000p

**Comment by takumi0530** [comment]
@hana-0612 さん、お待たせいたしました。再度ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること（--- は初期値として設定すること）**
「スポーツ・レジャー・」と不要な記号「・」が含まれています。
<img width="301" alt="スクリーンショット 2021-09-28 10 31 28" src="https://user-images.githubusercontent.com/76197191/135007628-ed8b4af9-300c-4b7f-9a27-8b81ef61accc.png">

- [x] **配送料の負担は、「---、着払い(購入者負担)、送料込み(出品者負担)」の3項目が表示されること（--- は初期値として設定すること）**
「送料こみ(出品者負担)」となっています。「送料込み(出品者負担)」の表示に修正をお願いいたします。
<img width="308" alt="スクリーンショット 2021-09-28 10 32 31" src="https://user-images.githubusercontent.com/76197191/135007747-55e4ee6c-c2c3-4fdc-ac06-3615c1279446.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by hana-0612** [comment]
ご指摘事項修正いたしました。

**Comment by takumi0530** [comment]
@hana-0612 さん、お待たせいたしました。再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。
※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/135186876-015b0924-5932-4806-9808-ad190f8e18d8.png)
